# Project Euler Challenges 1 - 20
---
All of these challenges come from the Project Euler website at:

[Project Euler Link](https://projecteuler.net/)

In [224]:
# Imports
import math
import time
import numpy as np
import pandas as pd

---
## Problem 1: Multiples of 3 and 5

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.

The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
#My solution:
s = 0

for x in range(1,1000):
    if x%3==0 or x%5==0:
        s += x

print(s)

# More succinct solution
# list_ = [i for i in range(3,1000) if i%3==0 or i%5==0]
# print(sum(list_))

233168


---
## Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


In [2]:
fibs = [1]
a = 1
while a<4000000:
    fibs.append(a)
    a=fibs[-1]+fibs[-2]
    
print([num for num in fibs if num%2==0])

solution = sum([num for num in fibs if num%2==0])
solution

[2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]


4613732

---
## Problem 3: Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?


I searched for some efficient ways of handling this problem and found this great method on stack overflow:

<img src="data/problem_3.png">

In [16]:
num = 600851475143

def getLargestPrime(num1):
    n = num1
    i = 2
    
    # This works is because i grows while n decreases
    while i*i <= n:
        
        # If n%i==0 then i is a factor of n, n/i>=2 excludes 1
        while n%i==0 and n/i>=2:
            n = n / i   # n cut in half
            print(f'i val: {i}, : n val: {n}')
        i+=1
    print(f'Greatest Prime Factor of: {str(int(num1))} is: {str(int(n))}')
    return(n)

getLargestPrime(num)

i val: 71, : n val: 8462696833.0
i val: 839, : n val: 10086647.0
i val: 1471, : n val: 6857.0
Greatest Prime Factor of: 600851475143 is: 6857


6857.0

---
## Problem 4: Largest palindrome product

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is:

$ 9009 = 91 × 99 $

Find the largest palindrome made from the product of two 3-digit numbers.


In [54]:
test = str(123)
plist = []

for i in range (100,1000):
    for j in range (100, 1000):
        product = i*j
        revproduct = "".join(reversed(str(product)))
        
        if product == int(revproduct) and product not in plist:
            plist.append(int(revproduct))
            #print(f'Product of: {str(i)} * {str(j)} = {str(product)}')
                      
print(f'Largest palindrome from product of two 3-digit nums is: {max(plist)}')

Largest palindrome from product of two 3-digit nums is: 906609


---
## Problem 5: Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [57]:
# One trick I learned for cutting the options down was to remove values 
# divisible by a larger one.
# For example, 2, 4, 5, and 10 are all divisble by 20, therefore a value 
# divisble by 20 will be divisible by all those. 
# Same logic used for 7 with 14, and 3, 6, 9 with 18.
# Also, since all numbers are divisble by 1, no need for that either.

# The answer has to be even because no even num is divisble into an odd one. 
# Also, 20 is the step range between values, because the value has to be 
# divisble by 20 as well as all the values under 20. 


# My solution using brute-force approach, not optimal, but works:
t0 = time.time()

for i in range(20,999999999, 20):
    if (i%11==0 and i%14==0 and
        i%13==0 and i%16==0 and
        i%17==0 and i%18==0 and 
        i%19==0 and i%20==0
        ):
        print(i)
        break

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")
        
# REALLY COOL SOLUTION
# This does not require programming at all. Compute the prime factorization 
# of each number from 1 to 20 and multiply the greatest power of each 
# prime together:
#
# 20 = 2^2 * 5
# 19 = 19
# 18 = 2 * 3^2
# 17 = 17
# 16 = 2^4
# 15 = 3 * 5
# 14 = 2 * 7
# 13 = 13
# 11 = 11
#ANSWER: 2^4 * 3^2 * 5 * 7 * 11 * 13 * 17 * 19 = 232 792 560

232792560
Executed in: 1.4530630111694336 Seconds


---
## Problem 6: Sum square difference

The sum of the squares of the first ten natural numbers is:

$ 1^2 + 2^2 + ... + 10^2 = 385 $

The square of the sum of the first ten natural numbers is:

$ (1 + 2+ ... + 10)^2 = 55^2 = 3025 $

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is:

$ 3025 − 385 = 2640 $ 

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [5]:
squares = 0
sumz = 0

t0 = time.time()

for i in range(1, 101):
    squares += i**2
    sumz += i

print(sumz**2 - squares)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

25164150
Executed in: 0.0 Seconds


---
## Problem 7: 10001st prime

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10,001st prime number?


In [61]:
count = 6
number = 0

# Note a variable state is created with initial value True. 
# This is needed so that if a number is divisible by another other than 1
# state can be set to False. 
# This allows a conditional statement to test the function for true or false
def isPrime(num):
    state = True
    for i in range(3, int(math.sqrt(num))+1):
        if num%i==0:
            state = False
            break
    return(state)
    
t0 = time.time()

for i in range(15, 1000000, 2):
    if isPrime(i) == True and count < 10001:
        count += 1
        number = i

print("Final solution at point count: " + str(count) + " is: " + str(number))
t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

Final solution at point count: 10001 is: 104743
Executed in: 6.094398736953735 Seconds


---
## Problem 8: Largest product in a series

This problems description is below due to large number value

In [63]:
from functools import reduce

# The four adjacent digits in the 1000-digit number that have the
# greatest product are 9 × 9 × 8 × 9 = 5832.

# Find the thirteen adjacent digits in the 1000-digit number that 
# have the greatest product. What is the value of this product?

num = """
73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
""".replace("\n", "")

# Creates a list of numbers with each num in an element
mnum = map(int, num)
listnum = list(mnum)
largestnum = 0

for i in range (0,1000):
    prodlist = listnum[i:i+13]
    # reduce() good for performing function on all list elements.
    testprod = reduce(lambda x, y: x*y, prodlist) 
            
    if testprod > largestnum:
        largestnum = testprod
        
print(largestnum)

23514624000


---
## Problem 9: Special Pythagorean triplet

A Pythagorean triplet is a set of three poistive integers such that:

$ a^2 + b^2 = c^2 $

For example:

$ 3^2 + 4^2 = 9 + 16 = 25 = 5^2 $

There exists exactly one Pythagorean triplet for which 

$ a + b + c = 1000 $

Find the product abc


**My solution used Euclid's fomrula for solving pythagoreum triples.**
**I read up on the subject and found this formula on Wikipedia:**

<img src="data/pyth_triples.PNG">

In [81]:
# My Solution using Euclid's formula:

for m in range(1,25):
    for n in range(1,25):
        if n < m:
            a = m**2 - n**2
            b = 2 * (m * n)
            c = m**2 + n**2
            
            if a + b + c == 1000:
                print(f'{a} + {b} + {c} = 1,000')
                print(f'solution: {a * b * c}')
                
                
# Brute force approach, much less efficient
#num = 0
#
#for i in range(1,500):
#    if num == 1000:
#        break
#    for j in range(1,500):
#        for k in range(1,500):
#            if i*i + j*j == k*k and i+j+k == 1000:
#                num = 1000
#                print(i*j*k)
#                break 

375 + 200 + 425 = 1,000
solution: 31875000


---
## Problem 10: Special Pythagorean triplet

The sum of the primes below 10 is:

$ 2 + 3 + 5 + 7 = 17 $

Find the sum of all the primes below two million.


In [4]:
# Solution 1: My Correct Brute Force Solution
def prime_chk(num):
    for i in range(2, int(math.sqrt(num))+1):
        if num%i==0:
            return False
    return True

def prime_sum(num):
    for i in range(3, num, 2):
        # Because looping only throuh odds, prime 2 is counted in sumtotal
        sumtotal = 2
        if prime_chk(i) == True:
            sumtotal += i
    print(f'The sum total of all primes below 2,000,000 is: {sumtotal}')

    
t0 = time.time()

prime_sum(2000000)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

The sum total of all primes below 2,000,000 is: 2
Executed in: 15.611000776290894 Seconds


In [50]:
# Solution 2
# Found on stack overflow: https://stackoverflow.com/questions/3939660/sieve-of-eratosthenes-finding-primes-python
# A much more efficient method than above using the Seive of Eratosthenes
# Algorithm for locating all primes below of a given number

def eratosthenes(n):
    non_primes =  set()  
    primes = set()
    
    # Start loop at 2 as 0, and 1 are not primes
    for i in range(2, n+1):
        
        # If i is not in non_primes, then it is a prime and needs to be added
        # to primes set
        if i not in non_primes:
            primes.add(i)
            
            # This section loops through all the multiples of i and adds
            # them to not_primes, so when this finishes and i loop restarts
            # if i is not in prime list, then it's prime.
            for j in range(i*i, n+1, i):
                non_primes.add(j)    # add() is used to append to a set
    #print(primes)
    print(sum(primes))
    

t0 = time.time()

num = 2000000  
eratosthenes(num)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

142913828922
Executed in: 1.1149983406066895 Seconds


In [51]:
# Solution 3
# Found in solutions for the problme on Project Euler

# An extremely efficient solution using the Sieve of Eratosthenes is 
# a very clever manner.

# This uses the index as the numbers to check, not the initial set up
# creates a list of 2 million True Statements and sets index 0 and 1 as false
# as 0 and 1 are not primes
def sieve(n):
    primes=[True]*(n+1)
    primes[0]=False
    primes[1]=False
    res=[]
    
    for i, prime in enumerate(primes):
        if prime: 
            primes[i**2:n+1:i]=[False]*len(primes[i**2:n+1:i])
            res.append(i)
    return sum(res)


t0 = time.time()

print(sieve(2000000))

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

142913828922
Executed in: 0.48799824714660645 Seconds


---
## Problem 11: Largest product in a grid

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

The product of these numbers is:

$ 26 × 63 × 78 × 14 = 1788696 $

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [77]:
grid =  '''
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
'''

nums = [int(i) for i in grid.split()]
nums = list(map(int, nums))
vectors  = [nums[i:i+20] for i in range(0,len(nums),20)]

# Creating vectors with loop
#vectors = []
#for i in range(0, len(nums), 20):
#    vectors.append(nums[i:i+20])

matrix = np.array(vectors)
print(f'Matrix Size: {matrix.shape}\n')
print(matrix)

# My Solution Using Numpy:
results = []
for i in range(17):
    for j in range(17):
        # Vertical
        vert = np.prod([matrix[i], matrix[i+1],
                        matrix[i+2], matrix[i+3]], axis=0).tolist()
        results.extend(vert)
        
        # Horizontal
        horz = np.prod(matrix[0:20, j:j+4], axis=1)
        results.extend(horz)
                
        # 4 X 4 sub-matrix created for diagonal calculations
        sub_matrix =  matrix[i:i+4, j:j+4]
        
        # Main Diagonals (left/right)
        diag = np.diagonal(sub_matrix).prod()
        results.append(diag2)
        
        # Opposite Diagonals (right/left)
        opp_diag = np.diagonal(np.fliplr(sub_matrix)).prod()
        results.append(opp_diag)
        
print(f'\nSolution: {max(results)}')

Matrix Size: (20, 20)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 

---
## Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

* 1: 1
* 3: 1,3
* 6: 1,2,3,6
* 10: 1,2,5,10
* 15: 1,3,5,15
* 21: 1,3,7,21
* 28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [171]:
nat_nums = list(range(1, 15000))
tri_nums = [sum(nat_nums[0:i+1]) for i in range(len(nat_nums))]

# My solution used brute force and was slow. I modified it after reviewing
# other more efficient methods below. 

# Good solution, note the 2 is added to each looped total to account
# for 1 and the number itself, this is needed because of using square root
def get_factors_loop(n):
    num_fact = 0
    for i in range(1, int(n**0.5) + 1):
        if (n % i == 0):
            num_fact += 2
    return num_fact


# This is an intersting one liner solution.
def get_factors(n):
    return sum(2 for i in range(1, round(math.sqrt(n)+1)) if not n % i)


for num in tri_nums:
    if get_factors_loop(num) > 499:
        print(num)
        break

76576500


---
## Problem 13: Large Sum

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [84]:
nums = '''
37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690'''

# My Solution using Numpy
str_vectors  = [nums[i:i+51].split() for i in range(0,len(nums),51)]
num_vectors  = [list(map(int, i)) for i in str_vectors]

matrix = np.array(num_vectors)

answer = list(matrix.sum(axis=0))

int(str(answer[0])[0:10])


# Alternate pure Python solution one liner, nice!
#x = (str(sum(int(x) for x in nums.split())))
#print(x[:10])

5537376230

---
## Problem 14: Longest Collatz sequence

The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:
13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.


In [130]:
import time

def collatz(num):
    seq = [num]  
    while num > 1:
        if num % 2 == 0 :
            num //= 2
            seq += [num]
        else: 
            num = (3 * num + 1) // 2
            seq += [num]     
    return(len(seq))         
             
start = time.time()
   
cur_max = 0
solution = 0
for i in range(1, 1_000_000, 2):
    seq_len = collatz(i)
    if seq_len > cur_max:
        cur_max = seq_len
        solution = i

print(f'Solution: {solution}')        
print(time.time() - start)

Solution: 837799
10.545760154724121


### I wasn't satisfied with my initial answer as it used brute force and took 10+ seconds to run, so I used a cache to store the sequence lengths and got the time down to approximately 2 seconds. 

In [166]:
import time

cache = {}

def collatz(num):
    seq_len = 0
    while num > 1:
        if num in cache:
            seq_len += cache[num]
            break
        else:
            if num % 2 == 0:
                num = num // 2
            else:
                num = num * 3 + 1
            seq_len += 1
    return(seq_len)   


def prob15(num):
    cur_max = 0
    solution = 0
    for i in range(1, num+1):
        cache[i] = collatz(i)   # cache, keys = i, values = seq_length
        if cache[i] > cur_max:
            cur_max = cache[i]
            solution = i
    

start = time.time()

prob15(1_000_000)

print(f'Solution: {solution}') 
print(f'Solution Sequence Length: {cache[837799]}')
print(f'Finished In: {time.time() - start} sec')

Solution: 837799
Solution Sequence Length: 524
Finished In: 1.9310979843139648 sec


---
## Problem 15: Lattice paths

Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?


Solution: 

Each move is either right or down and so can be represented as 1 or 0. Since the move is from one corner of a 20x20 grid to the opposite corner a total of 40 moves is required. 

A path, then, is logically equivalent to a 40 bit number 20 of whose bits are 0 and 20 are 1. So the number of paths is the number of permutations of 20 zeroes and 20 ones. 

That formula is taken from the binomial theorem, 40!/(20! * 20!). There are any number of ways to evaluate this number, some easier than others.

In [46]:
import math

n = 20

#solution = math.factorial(40)/(math.factorial(20) * math.factorial(20))
solution = math.factorial(n*2) / (math.factorial(n) **2)

print(solution)

137846528820.0


---
## Problem 16: Power digit sum

2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

In [26]:
# My Solution, I converted the number to a list of strings
# works ok, but the one liner without the list is better
def prob16(num):
    strings = list(str(num))
    return sum([int(x) for x in strings])

prob16(2**1000)

1366

In [27]:
# Good one liner for problem 16
print(sum([int(i) for i in str(2**1000)]))

1366


---
## Problem 17: Number letter counts

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.


In [3]:
def get1digit(num):
    one_d = {1 : 'one', 2 : 'two', 3 : 'three', 4 : 'four', 5 : 'five',
             6 : 'six', 7 : 'seven', 8 : 'eight', 9 : 'nine'}
    return(one_d[num])

def get2digit(num):
    two_d = {10 : 'ten', 11 : 'eleven', 12 : 'twelve', 13 : 'thirteen',
             14 : 'fourteen', 15 : 'fifteen', 16 : 'sixteen', 17 : 'seventeen',
             18 : 'eighteen', 19 : 'nineteen', 20  : 'twenty', 30  : 'thirty',
             40  : 'forty', 50  : 'fifty', 60  : 'sixty', 70  : 'seventy',
             80  : 'eighty', 90  : 'ninety'}
    
    if (len(str(num)) == 2 and num < 20) | (len(str(num)) == 2 and num % 10 == 0):
        return(two_d[num])
    else:
        return (f'{two_d[math.floor(num/10)*10]}{get1digit(int(str(num)[1]))}')
    
def get3digit(num):
    if num % 100 == 0:
        return (f'{get1digit(math.floor(num/100))}hundred')
    elif math.floor(num%100) < 10:
        return (f'{get1digit(math.floor(num/100))}hundredand{get1digit(math.floor(num%100))}')
    else:
        return (f'{get1digit(math.floor(num/100))}hundredand{get2digit(math.floor(num%100))}')
    
def prob17(max_val):
    answer = 0
    for i in range(1, max_val):
        if len(str(i)) == 1:
            answer += len(get1digit(i))    
        elif len(str(i)) == 2:
            answer += len(get2digit(i))
        elif len(str(i)) == 3:
            answer += len(get3digit(i))    
        else:
            s = 'onethousand'
            answer += len(s)
            
    return answer

s = time.time()
prob17(1001)  
print(time.time() - s)

0.006344318389892578


---
## Problem 18: Maximum path sum I

<img src="data/p18.png">

In [197]:
tri = '''
75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
'''

new_list = [list(map(int, x.split())) for x in tri.split('\n')]

f_list = []
for l in new_list:
    if len(l) > 0:
        f_list.append(l)
    
f_list

[[75],
 [95, 64],
 [17, 47, 82],
 [18, 35, 87, 10],
 [20, 4, 82, 47, 65],
 [19, 1, 23, 75, 3, 34],
 [88, 2, 77, 73, 7, 63, 67],
 [99, 65, 4, 28, 6, 16, 70, 92],
 [41, 41, 26, 56, 83, 40, 80, 70, 33],
 [41, 48, 72, 33, 47, 32, 37, 16, 94, 29],
 [53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14],
 [70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57],
 [91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48],
 [63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31],
 [4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]]

### Bottom Up Approach
The below approach uses dynamic programming without cache memoization to solve the problem

In [192]:
iterations = 0

t1 = time.time()

for i in reversed(range(len(f_list)-1)):
#for i in range(len(f_list)-2,-1,-1):
    for j in range(len(f_list[i])):
        f_list[i][j] += max(f_list[i+1][j], f_list[i+1][j+1])
        iterations += 1
    f_list.pop()
    #print(f_list[i])
    
print()
print(f'Solution: {f_list[0][0]}')
print(f'Iterations: {iterations}')
print(f'Time: {time.time()-t1}')


Solution: 1074
Iterations: 105
Time: 0.0006644725799560547


---
## Problem 19: Counting Sundays


You are given the following information, but you may prefer to do some research for yourself.

* 1 Jan 1900 was a Monday.
* 30 day monhts are: September, April, June and November
* 31 day months are all the rest aside from February
* February has 28 days on normal years and 29 days on leap years
* A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?


In [219]:
import datetime as dt

counter = 0
year = 1901
month = 1

day = dt.date(year, month, 1)

while day.year < 2001:
    if day.weekday() == 6:
        counter += 1
        
    if month+1 == 13:
        month = 1
        year += 1
    else:
        month += 1
        
    day = dt.date(year, month, 1)
        
print(counter)  

171


---
## Problem 20: Factorial digit sum

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!


In [237]:
solution = 0 
number = math.factorial(100)

for num in str(number):
    solution += int(num)
    
print(f'\nSolution: {solution}')


Solution: 648
