# Project Euler Challenges
---
All of these challenges come from the Project Euler website at:

[Project Euler Link](https://projecteuler.net/)

In [4]:
# Imports
import math
import time
import numpy as np
import pandas as pd

## Problem 1: Multiples of 3 and 5
---
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.

The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
#My solution:
s = 0

for x in range(1,1000):
    if x%3==0 or x%5==0:
        s += x

print(s)

# More succinct solution
# list_ = [i for i in range(3,1000) if i%3==0 or i%5==0]
# print(sum(list_))

233168


## Problem 2: Even Fibonacci numbers
---
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


In [2]:
fibs = [1]
a = 1
while a<4000000:
    fibs.append(a)
    a=fibs[-1]+fibs[-2]
    
print([num for num in fibs if num%2==0])

solution = sum([num for num in fibs if num%2==0])
solution

[2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]


4613732

## Problem 3: Largest prime factor
---
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

---

I searched for some efficient ways of handling this problem and found this great method on stack overflow:

<img src="data/problem_3.png">

In [16]:
num = 600851475143

def getLargestPrime(num1):
    n = num1
    i = 2
    
    # This works is because i grows while n decreases
    while i*i <= n:
        
        # If n%i==0 then i is a factor of n, n/i>=2 excludes 1
        while n%i==0 and n/i>=2:
            n = n / i   # n cut in half
            print(f'i val: {i}, : n val: {n}')
        i+=1
    print(f'Greatest Prime Factor of: {str(int(num1))} is: {str(int(n))}')
    return(n)

getLargestPrime(num)

i val: 71, : n val: 8462696833.0
i val: 839, : n val: 10086647.0
i val: 1471, : n val: 6857.0
Greatest Prime Factor of: 600851475143 is: 6857


6857.0

## Problem 4: Largest palindrome product
---
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is:

$ 9009 = 91 × 99 $

Find the largest palindrome made from the product of two 3-digit numbers.


In [54]:
test = str(123)
plist = []

for i in range (100,1000):
    for j in range (100, 1000):
        product = i*j
        revproduct = "".join(reversed(str(product)))
        
        if product == int(revproduct) and product not in plist:
            plist.append(int(revproduct))
            #print(f'Product of: {str(i)} * {str(j)} = {str(product)}')
                      
print(f'Largest palindrome from product of two 3-digit nums is: {max(plist)}')

Largest palindrome from product of two 3-digit nums is: 906609


## Problem 5: Smallest multiple
---
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [57]:
# One trick I learned for cutting the options down was to remove values 
# divisible by a larger one.
# For example, 2, 4, 5, and 10 are all divisble by 20, therefore a value 
# divisble by 20 will be divisible by all those. 
# Same logic used for 7 with 14, and 3, 6, 9 with 18.
# Also, since all numbers are divisble by 1, no need for that either.

# The answer has to be even because no even num is divisble into an odd one. 
# Also, 20 is the step range between values, because the value has to be 
# divisble by 20 as well as all the values under 20. 


# My solution using brute-force approach, not optimal, but works:
t0 = time.time()

for i in range(20,999999999, 20):
    if (i%11==0 and i%14==0 and
        i%13==0 and i%16==0 and
        i%17==0 and i%18==0 and 
        i%19==0 and i%20==0
        ):
        print(i)
        break

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")
        
# REALLY COOL SOLUTION
# This does not require programming at all. Compute the prime factorization 
# of each number from 1 to 20 and multiply the greatest power of each 
# prime together:
#
# 20 = 2^2 * 5
# 19 = 19
# 18 = 2 * 3^2
# 17 = 17
# 16 = 2^4
# 15 = 3 * 5
# 14 = 2 * 7
# 13 = 13
# 11 = 11
#ANSWER: 2^4 * 3^2 * 5 * 7 * 11 * 13 * 17 * 19 = 232 792 560

232792560
Executed in: 1.4530630111694336 Seconds


## Problem 6: Sum square difference
---
The sum of the squares of the first ten natural numbers is:

$ 1^2 + 2^2 + ... + 10^2 = 385 $

The square of the sum of the first ten natural numbers is:

$ (1 + 2+ ... + 10)^2 = 55^2 = 3025 $

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is:

$ 3025 − 385 = 2640 $ 

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [5]:
squares = 0
sumz = 0

t0 = time.time()

for i in range(1, 101):
    squares += i**2
    sumz += i

print(sumz**2 - squares)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

25164150
Executed in: 0.0 Seconds


## Problem 7: 10001st prime
---
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10,001st prime number?


In [61]:
count = 6
number = 0

# Note a variable state is created with initial value True. 
# This is needed so that if a number is divisible by another other than 1
# state can be set to False. 
# This allows a conditional statement to test the function for true or false
def isPrime(num):
    state = True
    for i in range(3, int(math.sqrt(num))+1):
        if num%i==0:
            state = False
            break
    return(state)
    
t0 = time.time()

for i in range(15, 1000000, 2):
    if isPrime(i) == True and count < 10001:
        count += 1
        number = i

print("Final solution at point count: " + str(count) + " is: " + str(number))
t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

Final solution at point count: 10001 is: 104743
Executed in: 6.094398736953735 Seconds


## Problem 8: Largest product in a series
---
This problems description is below due to large number value

In [63]:
from functools import reduce

# The four adjacent digits in the 1000-digit number that have the
# greatest product are 9 × 9 × 8 × 9 = 5832.

# Find the thirteen adjacent digits in the 1000-digit number that 
# have the greatest product. What is the value of this product?

num = """
73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
""".replace("\n", "")

# Creates a list of numbers with each num in an element
mnum = map(int, num)
listnum = list(mnum)
largestnum = 0

for i in range (0,1000):
    prodlist = listnum[i:i+13]
    # reduce() good for performing function on all list elements.
    testprod = reduce(lambda x, y: x*y, prodlist) 
            
    if testprod > largestnum:
        largestnum = testprod
        
print(largestnum)

23514624000


## Problem 9: Special Pythagorean triplet
---
A Pythagorean triplet is a set of three poistive integers such that:

$ a^2 + b^2 = c^2 $

For example:

$ 3^2 + 4^2 = 9 + 16 = 25 = 5^2 $

There exists exactly one Pythagorean triplet for which 

$ a + b + c = 1000 $

Find the product abc


**My solution used Euclid's fomrula for solving pythagoreum triples.**
**I read up on the subject and found this formula on Wikipedia:**

<img src="data/pyth_triples.png">

In [81]:
# My Solution using Euclid's formula:

for m in range(1,25):
    for n in range(1,25):
        if n < m:
            a = m**2 - n**2
            b = 2 * (m * n)
            c = m**2 + n**2
            
            if a + b + c == 1000:
                print(f'{a} + {b} + {c} = 1,000')
                print(f'solution: {a * b * c}')
                
                
# Brute force approach, much less efficient
#num = 0
#
#for i in range(1,500):
#    if num == 1000:
#        break
#    for j in range(1,500):
#        for k in range(1,500):
#            if i*i + j*j == k*k and i+j+k == 1000:
#                num = 1000
#                print(i*j*k)
#                break 

375 + 200 + 425 = 1,000
solution: 31875000


## Problem 10: Special Pythagorean triplet
---
The sum of the primes below 10 is:

$ 2 + 3 + 5 + 7 = 17 $

Find the sum of all the primes below two million.


In [4]:
# Solution 1: My Correct Brute Force Solution
def prime_chk(num):
    for i in range(2, int(math.sqrt(num))+1):
        if num%i==0:
            return False
    return True

def prime_sum(num):
    for i in range(3, num, 2):
        # Because looping only throuh odds, prime 2 is counted in sumtotal
        sumtotal = 2
        if prime_chk(i) == True:
            sumtotal += i
    print(f'The sum total of all primes below 2,000,000 is: {sumtotal}')

    
t0 = time.time()

prime_sum(2000000)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

The sum total of all primes below 2,000,000 is: 2
Executed in: 15.611000776290894 Seconds


In [50]:
# Solution 2
# Found on stack overflow: https://stackoverflow.com/questions/3939660/sieve-of-eratosthenes-finding-primes-python
# A much more efficient method than above using the Seive of Eratosthenes
# Algorithm for locating all primes below of a given number

def eratosthenes(n):
    non_primes =  set()  
    primes = set()
    
    # Start loop at 2 as 0, and 1 are not primes
    for i in range(2, n+1):
        
        # If i is not in non_primes, then it is a prime and needs to be added
        # to primes set
        if i not in non_primes:
            primes.add(i)
            
            # This section loops through all the multiples of i and adds
            # them to not_primes, so when this finishes and i loop restarts
            # if i is not in prime list, then it's prime.
            for j in range(i*i, n+1, i):
                non_primes.add(j)    # add() is used to append to a set
    #print(primes)
    print(sum(primes))
    

t0 = time.time()

num = 2000000  
eratosthenes(num)

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

142913828922
Executed in: 1.1149983406066895 Seconds


In [51]:
# Solution 3
# Found in solutions for the problme on Project Euler

# An extremely efficient solution using the Sieve of Eratosthenes is 
# a very clever manner.

# This uses the index as the numbers to check, not the initial set up
# creates a list of 2 million True Statements and sets index 0 and 1 as false
# as 0 and 1 are not primes
def sieve(n):
    primes=[True]*(n+1)
    primes[0]=False
    primes[1]=False
    res=[]
    
    for i, prime in enumerate(primes):
        if prime: 
            primes[i**2:n+1:i]=[False]*len(primes[i**2:n+1:i])
            res.append(i)
    return sum(res)


t0 = time.time()

print(sieve(2000000))

t1 = time.time()
print("Executed in: " + str(t1-t0) + " Seconds")

142913828922
Executed in: 0.48799824714660645 Seconds


## Problem 11: Largest product in a grid
---
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

The product of these numbers is:

$ 26 × 63 × 78 × 14 = 1788696 $

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [77]:
grid =  '''
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
'''

nums = [int(i) for i in grid.split()]
nums = list(map(int, nums))
vectors  = [nums[i:i+20] for i in range(0,len(nums),20)]

# Creating vectors with loop
#vectors = []
#for i in range(0, len(nums), 20):
#    vectors.append(nums[i:i+20])

matrix = np.array(vectors)
print(f'Matrix Size: {matrix.shape}\n')
print(matrix)

# My Solution Using Numpy:
results = []
for i in range(17):
    for j in range(17):
        # Vertical
        vert = np.prod([matrix[i], matrix[i+1],
                        matrix[i+2], matrix[i+3]], axis=0).tolist()
        results.extend(vert)
        
        # Horizontal
        horz = np.prod(matrix[0:20, j:j+4], axis=1)
        results.extend(horz)
                
        # 4 X 4 sub-matrix created for diagonal calculations
        sub_matrix =  matrix[i:i+4, j:j+4]
        
        # Main Diagonals (left/right)
        diag = np.diagonal(sub_matrix).prod()
        results.append(diag2)
        
        # Opposite Diagonals (right/left)
        opp_diag = np.diagonal(np.fliplr(sub_matrix)).prod()
        results.append(opp_diag)
        
print(f'\nSolution: {max(results)}')

Matrix Size: (20, 20)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 